### ISSUE TITLE
No module named 'doit'

### ISSUE THREAD

**Issue by HaFred** [firesim/FireMarshal#113]
When I tried to run marshal to build sha3 Bare-Metal test with:
`./marshal build example-workloads/sha3/marshal-configs/sha3-bare-rocc.json`

Errors occurred like below, and I could not find out any dependencies related to 'doit' to install. 
`Traceback (most recent call last):
  File "./marshal", line 6, in <module>
    import wlutil
  File "/home/frederick/workspace/chipyard/sims/firesim/sw/firesim-software/wlutil/__init__.py", line 6, in <module>
    from .build import buildWorkload 
  File "/home/frederick/workspace/chipyard/sims/firesim/sw/firesim-software/wlutil/build.py", line 1, in <module>
    import doit
ModuleNotFoundError: No module named 'doit'`

Thanks in advance!

**Comment by HaFred** [comment]
Solved by `sudo python3 -m pip install doit`.
