### ISSUE TITLE
Workdir arg error

### ISSUE THREAD

**Issue by alonamid** [firesim/FireMarshal#132]
```
centos@ip-192-168-0-102 firesim-software]$ ./marshal -v --workdir /home/centos/some-dir build some-workload.json
Traceback (most recent call last):
  File "./marshal", line 201, in <module>
    main()
  File "./marshal", line 98, in main
    cfgs = wlutil.ConfigManager(workdirs.keys())
  File "/home/centos/chipyard-ee290/sims/firesim/sw/firesim-software/wlutil/config.py", line 356, in __init__
    for cfgFile in d.glob('*.json'):
AttributeError: 'str' object has no attribute 'glob'

```

Potential solution: 
```
diff --git a/wlutil/config.py b/wlutil/config.py
index 21ea519..9b44678 100644
--- a/wlutil/config.py
+++ b/wlutil/config.py
@@ -353,7 +353,7 @@ class ConfigManager(collections.MutableMapping):
         if dirs != None:
             for d in dirs: 
-                for cfgFile in d.glob('*.json'):
+                for cfgFile in pathlib.Path(d).glob('*.json'):
                     cfgPaths.append(cfgFile)
         # First, load the base-configs specially. Note that these are indexed

```

**Comment by NathanTP** [comment]
fixed by #133
