### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Yuxin-Yu** [firesim/FireMarshal#243]
Hi,I build FireMarshal environment in Chipyard/software/firemarshal.I executed "./init-submodules.sh" and download all of the submodule.Then I run "./marshal build br-base.json",I got this error:
[ICer@IC_EDA /home/ICer/riscv/projects/chipyard/software/firemarshal]$./marshal build br-base.json
Traceback (most recent call last):
  File "./marshal", line 228, in <module>
    main()
  File "./marshal", line 75, in main
    wlutil.initialize()
  File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/wlutil.py", line 398, in initialize
    ctx = marshalCtx()
  File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/wlutil.py", line 238, in __init__
    self.addPath(src)
  File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/wlutil.py", line 272, in addPath
    cleanPaths(newCfg, baseDir=path.parent)
  File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/wlutil.py", line 122, in cleanPaths
    if opt in opts and opts[opt] is not None:
TypeError: string indices must be integers
 
Could you tell me how to fix it,thanks.

**Comment by Yuxin-Yu** [comment]
The problem was solved because I entered wrong board information in marshal-config.yaml.Sorry
