### ISSUE TITLE
TaskError when builing workload

### ISSUE THREAD

**Issue by JimmyWong1998** [firesim/FireMarshal#291]
Hi FireMarshal experts,

I am new to use FireMarshal and I want to build the software with chipyard. Following the instruction to build  the workload, I got an TaskError as shown in the below code section. Could you help me solve that problem?

PS:  I try to understand that TaskError tells me it wants to run br.ee10.img but I find my  /root/chipyard/software/firemarshal/images/ is empty. Could you also help me whether my understanding is correct?

```
root@63945a200c69:~/chipyard/software/firemarshal# marshal build br-base.json
WARNING: Unrecognized Option: version
WARNING: Unrecognized Option: sphinx
WARNING: Skipping /root/chipyard/software/firemarshal/.readthedocs.yaml:
WARNING: 	Missing required option 'name'
WARNING: Unrecognized Option: firesim-dir
WARNING: Skipping /root/chipyard/software/firemarshal/marshal-config.yaml:
WARNING: 	Missing required option 'name'
To check on progress, either call marshal with '-v' or see the live output at: 
/root/chipyard/software/firemarshal/logs/br-base-build-2023-10-22--02-40-19-GZUKCYQI8FJWIQB6.log
.  /root/chipyard/software/firemarshal/boards/firechip/base-workloads/br-base/host-init.sh 
Applying host-init: /root/chipyard/software/firemarshal/boards/firechip/base-workloads/br-base/host-init.sh 
.  /root/chipyard/software/firemarshal/images/br.ee10.img
TaskError - taskid:/root/chipyard/software/firemarshal/images/br.ee10.img
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/root/chipyard/software/firemarshal/boards/firechip/distros/br/br.py", line 190, in buildBaseImage
    wlutil.run(['make'], cwd=br_dir / "buildroot", env=env)
  File "/root/chipyard/software/firemarshal/wlutil/wlutil.py", line 498, in run
    raise sp.CalledProcessError(p.returncode, prettyCmd)
subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.

ERROR: Failed to build workload br-base.json
Log available at: /root/chipyard/software/firemarshal/logs/br-base-build-2023-10-22--02-40-19-GZUKCYQI8FJWIQB6.log
```

Many thanks,
Jimmy

**Comment by RealJustinNi** [comment]
I have the same issue. The path “chipyard/software/firemarshal/images/” is empty.
