### ISSUE TITLE
Building br-base.json for prototyping fails (unable to download cached image)

### ISSUE THREAD

**Issue by ktlpdlbr** [firesim/FireMarshal#312]
Hi I am following the instructions given in [chipyard documentation](https://chipyard.readthedocs.io/en/latest/Prototyping/VCU118.html#building-linux-with-firemarshal) to build linux image for my FPGA prototype however building it I have following logs: 

` [buildBaseIma] [INFO ]  Attempting to download cached image: https://raw.githubusercontent.com/firesim/firemarshal-public-br-images/main/images/prototype/br.b8b4/br.b8b4.img.zip
 [buildBaseIma] [DEBUG]  urlretrieve exception: HTTP Error 404: Not Found
 [run         ] [DEBUG]  Running: "make defconfig" in /chipyard/software/FireMarshal/boards/prototype/distros/br/buildroot
 [run         ] [DEBUG]  mkdir -p /chipyard/software/FireMarshal/boards/default/distros/br/buildroot/output/build/buildroot-config/lxdialog`

And in the end, it fails with the following logs:

`DEBUG: make[1]: *** [package/pkg-generic.mk:273: /chipyard/software/FireMarshal/boards/default/distros/br/buildroot/output/build/toolchain-external-custom/.stamp_configured] Error 1
DEBUG: make: *** [Makefile:82: _all] Error 2
TaskError - taskid:/chipyard/software/FireMarshal/images/prototype/br.b8b4/br.b8b4.img
PythonAction Error
Traceback (most recent call last):
  File "/chipyard/.conda-env/lib/python3.10/site-packages/doit/action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/chipyard/software/FireMarshal/boards/prototype/distros/br/br.py", line 271, in buildBaseImage
    wlutil.run(['make'], cwd=br_dir / "buildroot", env=env)
  File "/chipyard/software/FireMarshal/wlutil/wlutil.py", line 527, in run
    raise sp.CalledProcessError(p.returncode, prettyCmd)
subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.`

**Comment by Jerryy959** [comment]
I have the same issue

**Comment by Jerryy959** [comment]
> Hi I am following the instructions given in [chipyard documentation](https://chipyard.readthedocs.io/en/latest/Prototyping/VCU118.html#building-linux-with-firemarshal) to build linux image for my FPGA prototype however building it I have following logs:
> 
> `[buildBaseIma] [INFO ] Attempting to download cached image: https://raw.githubusercontent.com/firesim/firemarshal-public-br-images/main/images/prototype/br.b8b4/br.b8b4.img.zip` `[buildBaseIma] [DEBUG] urlretrieve exception: HTTP Error 404: Not Found` `[run] [DEBUG] Running: "make defconfig" in /chipyard/software/FireMarshal/boards/prototype/distros/br/buildroot` `[run] [DEBUG] mkdir -p /chipyard/software/FireMarshal/boards/default/distros/br/buildroot/output/build/buildroot-config/lxdialog`
> 
> And in the end, it fails with the following logs:
> 
> `DEBUG: make[1]: *** [package/pkg-generic.mk:273: /chipyard/software/FireMarshal/boards/default/distros/br/buildroot/output/build/toolchain-external-custom/.stamp_configured] Error 1` `DEBUG: make: *** [Makefile:82: _all] Error 2` `TaskError - taskid:/chipyard/software/FireMarshal/images/prototype/br.b8b4/br.b8b4.img` `PythonAction Error` `Traceback (most recent call last):` `File "/chipyard/.conda-env/lib/python3.10/site-packages/doit/action.py", line 461, in execute returned_value = self.py_callable(*self.args, **kwargs)` `File "/chipyard/software/FireMarshal/boards/prototype/distros/br/br.py", line 271, in buildBaseImage wlutil.run(['make'], cwd=br_dir / "buildroot", env=env)` `File "/chipyard/software/FireMarshal/wlutil/wlutil.py", line 527, in run raise sp.CalledProcessError(p.returncode, prettyCmd)` `subprocess.CalledProcessError: Command 'make' returned non-zero exit status 2.`


<img width="733" alt="截屏2024-10-27 19 16 22" src="https://github.com/user-attachments/assets/e9b4e23e-78ec-4cf6-9570-d934763da369">

I guess you have already running this command, but the correspond repo: https://github.com/firesim/firemarshal-public-br-images/tree/main seems that there is no prototype dir.

**Comment by Jerryy959** [comment]
and if i delete the file <marshal-config.yaml>, everything works fine.

**Comment by panjin12345** [comment]
I have the same problem, here is my log report:
[br-base-build-2024-11-10--11-27-20-SC1LFS8KCDQ28IRT.log](https://github.com/user-attachments/files/17691610/br-base-build-2024-11-10--11-27-20-SC1LFS8KCDQ28IRT.log)

**Comment by Jerryy959** [comment]
@abejgonzalez @NathanTP

**Comment by ipapal** [comment]
Is there any update?

**Comment by rfgIII** [comment]
Is there an update on this issue? I cleared the cache in the buildroot and ran the fix-open-files.sh to check the limit on my system. Still running into the same issue.
